Rewrite HMD Projection Matrix
gray-armor/z11 pull request #17
Opened 2021-07-30 14:56 UTC by shierote

Fix https://github.com/gray-armor/z11/issues/16

2021-07-30 15:02 UTC, Aki-7 requested changes

2021-07-30 15:02 UTC, Aki-7 commented on compositor/hmd.cc
> +      0, 0, e, 0   //
ここ、視野各に関する設定ができてない気がする

https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetProjectionRaw

2021-08-01 12:43 UTC, shierote commented on compositor/hmd.cc
> +      0, 0, e, 0   //
うっかりしてた、今から直す
（z軸の変換も入れるのでちょい時間かかるかも）

2021-08-01 16:38 UTC, Aki-7 commented on compositor/hmd.cc
> +      0, 0, -2 * far * near * dz, 0                 //
```suggestion
  return Matrix4(                                   //
      2 * dx, 0, 0, 0,                              //
      0, 2 * dy, 0, 0,                              //
      -sx * dx, -sy * dy, (far + near) * dz, 1.0f,  //
      0, 0, -far * near * dz, 0                 //
```

![IMG_C4E49174E8AC-1](https://user-images.githubusercontent.com/44729662/127778617-e124597e-b4df-4f44-9210-d8dd634e9349.jpeg)

2021-08-02 09:19 UTC, shierote commented on compositor/hmd.cc
> +      0, 0, -2 * far * near * dz, 0                 //
コレもちろん試したんだけど上手く行かないんよね（HMDが向いた方向に3Dモデルがついてきてしまう + 世界座標系もz軸がマイナスが正面のまま）
視錐台のz軸を反転させても上手く行かなさそう
View Matrixの向きも合ってそうなんだよね。。もうちょい調べてみる。

ちなみに 2* にしてるのは床井さんの記事の内容を参考にしてる。どっちでも良さそう。
https://marina.sys.wakayama-u.ac.jp/~tokoi/?date=20090829

2021-08-02 09:46 UTC, Aki-7 commented on compositor/hmd.cc
> +      0, 0, -2 * far * near * dz, 0                 //
2* するのはz軸をNDCのz軸の[-1, 1]に写像する時で、[0, 1]に写像する時は2*しないみたいだね
OpenGLはデフォルトでNDCの[-1, 1]をクリッピングするみたいだから2*が必要そうでした。
2*で、符号を反転させたのも試した？

2021-08-02 09:50 UTC, shierote commented on compositor/hmd.cc
> +      0, 0, -2 * far * near * dz, 0                 //
それも試したけどダメだった。
何も描画されない。

2021-08-02 09:51 UTC, Aki-7 commented on compositor/hmd.cc
> +    viewProjection = head_to_view_projection_right_ * head_pose_ * right_handed_coordinate_to_left_;
ここは消してる？

```suggestion
    viewProjection = head_to_view_projection_right_ * head_pose_;
```

2021-08-02 09:55 UTC, Aki-7 reviewed
このPRの前の時点ではうまくいってたなら、
HMD::ProjectionMatrix
だけIVRSystem::GetProjectionRaw
を使って書き換えられるのかとかをまず見てみるのがいいんじゃないかな。

IVRSystem::GetProjectionRawが想像してるものと違ったりしてそう。

2021-08-02 09:56 UTC, shierote commented on compositor/hmd.cc
> +    viewProjection = head_to_view_projection_right_ * head_pose_ * right_handed_coordinate_to_left_;
消してるよ

2021-08-02 09:59 UTC, shierote commented
おけ。
-no-hmdだと想定の動作になるからできるはずではあるんよね、もうちょい待ってほしい
いろいろ提案あざす

2021-08-02 14:34 UTC, shierote commented
-no-hmdの方も視点の変化の方向変えると、その方向に3Dモデルが動いちゃうから間違ってた（けどview行列が変化しないから問題ないんだけど）。

右側を向くview行列
```
0.798592, -0.045102, -0.600180, 0.000000,
-0.041038, 0.990787, -0.129061, 0.000000,
0.600472, 0.127697, 0.789384, 0.000000,
-0.232399, -0.568074, 0.613423, 1.000000
```

2021-08-02 15:26 UTC, shierote commented
コレでz軸は上手く行くんだけどx軸y軸の向きは逆になってしまう
```:hmd.cc
  Matrix4 mat = Matrix4(                            //
      2 * dx, 0, 0, 0,                              //
      0, 2 * dy, 0, 0,                              //
      sx * dx, sy * dy, -(far + near) * dz, -1.0f,  //
      0, 0, -far * near * dz, 0                     //
  );

  Matrix4 inverse = Matrix4(  //
      -1, 0, 0, 0,            //
      0, -1, 0, 0,            //
      0, 0, -1, 0,            //
      0, 0, 0, 1              //
  );

  return mat * inverse;
```

2021-08-02 15:31 UTC, Aki-7 commented
inverseを-1, -1, -1, 1 --> 1, 1, -1, 1 にしたら良いとかではないの？

2021-08-02 16:37 UTC, shierote commented
うんそれはできそうだけどできない。

2021-08-02 16:47 UTC, Aki-7 commented
まぁ、そしたらつまり
https://github.com/gray-armor/z11/pull/17#discussion_r680535681
これだもんね。
謎だな

2021-08-02 16:48 UTC, shierote commented
できない理由がわかった気がするのでコメントで追記する。
次zoomするときも話させてほしい。

2021-08-02 16:54 UTC, shierote commented
で、結局選択肢としては、
1. PR出す前の状況に戻す（Viewの右側からz軸を変換する行列を毎度かける）
2. Client側でz軸を変換する行列をかける（コレはだいぶイマイチ）
3. マイナスz軸方向が正面であるというルールにする。
僕は、選択肢3派。 @Aki-7 は？

2021-08-02 16:59 UTC, Aki-7 commented
1かなー
3の場合、右手系?左手系?

2021-08-02 17:02 UTC, shierote commented
3は左手系だね。
じゃあ1にしようか。

2021-08-02 17:02 UTC, Aki-7 commented
1でも3でもいいけど、内部実装の都合じゃなくて何が自然かで考えたいな。
ただ何が自然なのかよくわからんから、今度経験のある方に聞くのが良さそう？

2021-08-02 17:03 UTC, Aki-7 commented
ん、1は右手系てこと？

2021-08-02 17:03 UTC, shierote commented
そうしよう、とりあえず1で良いと思う。
clientで-zを入力するのめんどくさいし（完全に開発側の都合だけど）

2021-08-02 17:03 UTC, shierote commented
1は右手系

2021-08-02 17:07 UTC, shierote commented
Projection Matrixでz軸だけを反転させるのが無理そうな理由。
![メモ-2](https://user-images.githubusercontent.com/32413673/127898426-8ef1a6e9-e818-4992-b0c4-d1b07a2babca.jpg)

2021-08-02 17:10 UTC, shierote commented
あ、ごめん逆だった
3は右手系で、1とかmasterのSDLが左手系
すまん

2021-08-02 17:15 UTC, shierote commented
ということでこのPRは閉じます。
issueは開いといて、識者への相談会で聞くことリストとして残しておきます。

2021-08-02 17:15 UTC, closed without merging

2021-08-02 17:19 UTC, Aki-7 commented
そっか、そこにPoseのMatrixが入るのかなるほどね

OpenVRの仕様がよくわからないの問題だな内部実装も見れないし。
実際に飛んでくるデータ見るしかないのかな

2021-08-02 17:21 UTC, Aki-7 commented on compositor/hmd.cc
> +  );
closeでいいと思うけど、ここのpose.m[*][2]に - つけるのとか計算ほとんど増えなくていいかもね

2021-08-02 17:23 UTC, shierote commented on compositor/hmd.cc
> +  );
それも考えたけどその後invertしてるんよね...
難しい

2021-08-02 17:25 UTC, Aki-7 commented on compositor/hmd.cc
> +  );
なるほどー笑

2021-08-02 17:28 UTC, Aki-7 commented on compositor/hmd.cc
> +  );
poseってきっと平行移動と回転で作られる正則行列だと考えるとうまいこと計算できはするはずだけど、まぁとりあえずほっとこう