Add STL Viewer client
gray-armor/z11 pull request #26
Opened 2021-08-04 16:49 UTC by shierote

Fix #23 
STL Viewerを実装した。

2021-08-05 06:41 UTC, shierote commented
STLファイルの頂点が必ずしも(0, 0, 0)を中心にしているとは限らないので位置移動の演算をする必要があるが、
Model MatrixをClientから送れるようにして、compositor側で演算できるようにしたほうが良さそう。
ということで、行列を送信・利用するProtocolを先に実装する。

2021-08-05 06:42 UTC, Aki-7 commented
Model Matrixてなんだっけ？

2021-08-05 06:45 UTC, Aki-7 commented
Matixを作ってshaderで利用できるようにして、位置移動の計算はshaderで記述してGPUにやらせよう的な意味かな？

2021-08-05 07:08 UTC, shierote commented
あーそうそう
Model Matrixは各Clientの相対座標を世界座標に変換する行列
simple boxのx, y, zとか回転とかも本当はModel Matrix作って記述できると綺麗だなと。
STLも同様。

でshader内にmodelを指定しても良いし、ViewProjectionに掛けてMVPをshaderのmatrixにしても良さそう。

2021-08-05 07:16 UTC, Aki-7 commented
なるほどねん、Model Matrixはクライアントが作成・利用できるべきか微妙なとこだよね。
ユーザがCuboid Windowを操作して平行移動や回転移動をするなら、Model MatrixはCompositorが管理して、MVPの形でしかクライアントは(shaderで)利用できない。とした方がいいかもしれなさそう。

今のところはModel Matrixは単位行列に固定ということにして、今回は単純にユーザが自由にMatrixを作れてそれをshaderで利用できる、くらいが良さそうな気もする。どうだろ、もしくはそのつもり？

2021-08-05 12:06 UTC, Aki-7 commented
試してみたけど、いいね

2021-08-05 12:32 UTC, shierote commented
> 今のところはModel Matrixは単位行列に固定ということにして、今回は単純にユーザが自由にMatrixを作れてそれをshaderで利用できる、くらいが良さそうな気もする。どうだろ、もしくはそのつもり？
ユーザー=Clientよね、うん、このPRではそうするわ
shader内にmatrixの値も埋め込む

2021-08-05 18:13 UTC, Aki-7 commented
pngやstlに関するコードはhelperじゃない方がいい気もしてきた

2021-08-06 12:57 UTC, shierote commented
helperじゃないほうがよいというのは、各Clientのコードに記述したほうが良いということ？
helperをフォルダにして機能ごとにファイル分けても良さそう

とりあえずこのPRではコレで良いんじゃないかなー
必要ならあとからRefactor系のPR送るわ

2021-08-06 13:19 UTC, shierote commented
これready for reviewにしちゃったけど、STLモデルの拡大縮小・平行移動だけできるようにするのでちょいお待ちを（あんまりコード変わらないと思うけど）

2021-08-06 13:29 UTC, Aki-7 commented on protocol/z11.xml
> +      <entry name="polygon" value="9"/>
今までのz11.xmlは一応Vulkanにも対応できるように書いてたんだよね。Vulkan詳しくないからほんとに対応できてるかはわからないけど。
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPrimitiveTopology.html
quadsとかいくつかのAPIはVulkanとは対応してないからどうしようかなと思う。
OpenGLでしか作らない。としてもいいかもなんだけどどう思う？

2021-08-06 13:43 UTC, shierote commented on protocol/z11.xml
> +      <entry name="polygon" value="9"/>
なるほどね、quadsとかpolygonはとりあえず使わなくてもしばらく問題なさそうだから消すわ。
未登期間でできるかわからないけどVulkanにはいずれ対応したいよね

2021-08-06 15:42 UTC, Aki-7 commented
reviewできる感じになったら教えてくださいな

2021-08-06 16:31 UTC, Aki-7 requested changes
TOPOLOGY_LINESのとこだけおかしそうだから、みてみて欲しい。
他は任せます。

2021-08-06 16:31 UTC, Aki-7 commented on clients/helper.c
> +  }
```c
typedef struct {
  Point normal;
  Point v1, v2, v3;
  uint16_t unused;
} Facet;
```
こういうのを定義して

```c
freed(facet, sizeof(Facet), *face_count, fp);
```
こんな感じで一回で読み込んだ方がコードが綺麗になりそう。

2021-08-06 16:31 UTC, Aki-7 commented on clients/helper.c
> +  }
`set_point_from_stl`とかいらなくなるんじゃないかな

2021-08-06 16:31 UTC, Aki-7 commented on clients/stl_viewer.c
> +  z11_render_block_set_topology(frame_render_block, Z11_GL_TOPOLOGY_LINES);
vertex_bufferの中身が三つの点がひと並びになって三角形を意味する構造になってるはずだから、そのままでZ11_GL_TOPOLOGY_LINESを使って描画は出来なさそう。

2021-08-06 16:31 UTC, Aki-7 commented on clients/stl_viewer.c
> +  z11_render_block_set_topology(frame_render_block, Z11_GL_TOPOLOGY_LINES);
実際描画してみたら、変なとこに線が入ったりしてた。

2021-08-06 16:31 UTC, Aki-7 commented on clients/stl_viewer.c
> +  z11_render_block_append_vertex_input_attribute(  //
// による改行が必要？
clang-configの改行設定が110文字だから、もし江口的に長すぎってことならそちらを直すのはありだと思うんだけど、他のコードも影響受けるから、別PRがいいと思うな

2021-08-06 18:33 UTC, shierote commented on clients/stl_viewer.c
> +  z11_render_block_set_topology(frame_render_block, Z11_GL_TOPOLOGY_LINES);
この問題ね、認知してたけど記述し忘れてた。
そのとおりで、STLは三角形の座標データの集合だからおかしくなってしまう。
で、GL_TRIANGLES使うと、影がないから立体感が失われてしまう。
だから選択肢は二択かなと思ってて、
- GL_TRIANGLESと共に、glPolygonModeをCompositor側で用いて、第二引数でGL_LINEを指定する。
- GL_LINESを用いて、STLの各三角形の頂点を、v1,v2, v2,v3, v3,v1の順で六頂点追加する。（Compositorはいじらなくてよいけど頂点データ量が2倍になってしまう。）
僕は前者のほうが今後の実装的には良いかなと思うけど、@Aki-7 はどう思う？

2021-08-06 18:34 UTC, shierote commented on clients/stl_viewer.c
> +  z11_render_block_set_topology(frame_render_block, Z11_GL_TOPOLOGY_LINES);
あと変な線が入るSTLファイルをもらえると嬉しい。

2021-08-06 18:36 UTC, shierote commented on clients/stl_viewer.c
> +  z11_render_block_append_vertex_input_attribute(  //
これは僕の環境のVSCodeで, このコメントを入れないと、スペースが奇数になってWarningがでちゃうからこうしてたんだけど、どうしようかなー
ちょっとextensionの設定をいじれないか調べてみる。

2021-08-06 18:39 UTC, shierote commented on clients/helper.c
> +  }
あーそれね、検討して、shm_dataに渡しづらいかなと思ったけど、
z11_render_block_append_vertex_input_attribute で頂点の位置を指定すれば良いか
もう一回検討します。

2021-08-07 04:45 UTC, Aki-7 commented on clients/stl_viewer.c
> +  z11_render_block_set_topology(frame_render_block, Z11_GL_TOPOLOGY_LINES);
サンプルのファイルよー
例えば注ぎ口の先端から蓋の方に一本線が出てたりする。

2021-08-07 04:55 UTC, Aki-7 commented on clients/stl_viewer.c
> +  z11_render_block_set_topology(frame_render_block, Z11_GL_TOPOLOGY_LINES);
> GL_TRIANGLESと共に、glPolygonModeをCompositor側で用いて、第二引数でGL_LINEを指定する

こっちの方がいいと思う。ちょっと大きめだから、とりあえずPOLYGON_TRIANGLEにして、これはマージしちゃうのもありかも

2021-08-07 05:29 UTC, Aki-7 commented on clients/helper.c
> +  }
それでもいいと思うし、今みたいに戻り値をFaceの形で返すために変換するとしても(char *)で受け取るより楽になるとおもう。

2021-08-07 05:33 UTC, Aki-7 commented on clients/helper.c
> +  }
```c
typedef struct {
  Point normal;
  Face face;
  uint16_t unused;
} Facet;
```
と定義すれば loopの中で
```c
Face *ret_val;
Facet *data;
// initialize pointers and fill facet data
for (int i = 0; i < (int)*face_count; i++) {
    ret_val[i] = data[i].face;
}
return ret_val;
```
とかで済むんじゃないかな

2021-08-07 05:36 UTC, Aki-7 commented
あ、あとせっかくだからclientsのREADME書いた方がいいかも

2021-08-07 06:44 UTC, Aki-7 commented on clients/helper.c
> +  }
でも、pointer attrib使った方がいいかもね、法線ベクトルとか今後使えるかもだし、任せます

2021-08-08 15:15 UTC, shierote commented
glPolygonModeへの対応は追いPRします。
glPolygonModeでLINEを指定して、GL_TRIANGLESの描画結果は、こんな感じ。
![Screenshot from 2021-08-09 00-13-55](https://user-images.githubusercontent.com/32413673/128636906-54ee97e1-976a-4067-8319-7c91fe3f4484.png)

2021-08-08 15:56 UTC, Aki-7 approved these changes

2021-08-08 16:34 UTC, shierote commented on clients/helper.c
> +  }
```:main.c
typedef struct {
  Point normal;
  Point v1, v2, v3;
  uint16_t unused;
} Facet;
```
これだとアライメントの制約で、50バイトじゃなくて52バイトになっちゃうんよね
だから
```:main.c
fread(facets, sizeof(Facet), *face_count, fp);
```
これだとちゃんと意図通りに読み込めない

FYI: https://ja.wikipedia.org/wiki/%E3%83%87%E3%83%BC%E3%82%BF%E6%A7%8B%E9%80%A0%E3%82%A2%E3%83%A9%E3%82%A4%E3%83%A1%E3%83%B3%E3%83%88

2021-08-08 16:38 UTC, Aki-7 commented on clients/helper.c
> +  }
`__attribute__((packed))` とか使ってアライメントをさせないようにできたと思う。

2021-08-08 16:39 UTC, Aki-7 commented on clients/helper.c
> +  }
たしかにアライメントは考えてなかった。

2021-08-08 16:40 UTC, Aki-7 commented on clients/helper.c
> +  }
なんでSTLファイル余計な2バイト足したんだろうね。

2021-08-08 16:42 UTC, Aki-7 commented on clients/helper.c
> +  }
```c
typedef struct __attribute__((packed)) {
  Point normal;
  Point v1, v2, v3;
  uint16_t unused;
} Facet;
```
かな

2021-08-08 18:54 UTC, shierote commented
残ってる実装は追ってPR出します。

2021-08-08 18:54 UTC, merged